targets:
    $default:
      builders:
        json_serializable:
          options:
            explicit_to_json: true
            generic_argument_factories: true
        freezed:
          options:
            any_map: true