name: tour_booking
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.2.2
  provider: ^6.1.5
  flutter_secure_storage: ^9.0.0
  pinput: ^5.0.1
  easy_localization: ^3.0.7+1
  flutter_dotenv: ^5.2.1
  change_app_package_name: ^1.5.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  google_sign_in: ^6.1.5
  onesignal_flutter: ^5.3.4
  shared_preferences: ^2.5.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/translations/
   - .env
