name: tour_booking
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.2.2
  provider: ^6.1.5
  flutter_secure_storage: ^9.0.0
  pinput: ^5.0.1
  easy_localization: ^3.0.7+1
  flutter_dotenv: ^5.2.1
  change_app_package_name: ^1.5.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  google_sign_in: ^6.1.5
  onesignal_flutter: ^5.3.4
  shared_preferences: ^2.5.3
  intl_phone_field: ^3.2.0
  app_links: ^6.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  firebase_storage: ^12.4.10
  flutter_debouncer: ^2.0.0
  flutter_toggle_tab: ^1.5.1
  intl: ^0.20.2
  toggle_switch: ^2.3.0
  decimal: ^3.2.4
  google_places_flutter: ^2.1.0
  flutter_time_picker_spinner: ^2.0.0
  cached_network_image: ^3.4.1
  sign_in_with_apple: ^7.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/translations/
   - .env.ios
   - .env.android

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"                # Arka plan rengi
  image: assets/splash.png        # Splash görseli
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  
