// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvZdocfp6ajN8Wsu6ykXexKQ1iiOh5wUg',
    appId: '1:423047904244:web:be17cbaec3a808dd2d57a1',
    messagingSenderId: '423047904244',
    projectId: 'tourbooking-e49bf',
    authDomain: 'tourbooking-e49bf.firebaseapp.com',
    storageBucket: 'tourbooking-e49bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ6aSAvIbV1ne-7wFkjdV_mr73OBBWris',
    appId: '1:423047904244:android:ab395375cf3b5a692d57a1',
    messagingSenderId: '423047904244',
    projectId: 'tourbooking-e49bf',
    storageBucket: 'tourbooking-e49bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlt-pSMoHoOyAGXOWyNOaun1O5OhEMPQ',
    appId: '1:423047904244:ios:562d2386e98b498e2d57a1',
    messagingSenderId: '423047904244',
    projectId: 'tourbooking-e49bf',
    storageBucket: 'tourbooking-e49bf.firebasestorage.app',
    iosClientId: '423047904244-30kirp95iq53kvltrijiuf12copgit59.apps.googleusercontent.com',
    iosBundleId: 'com.tourbooking.app',
  );

}